#!/usr/bin/env python3
"""commons_media.py — the ONE Wikimedia Commons fetch/encode/licence helper.

Both media pipelines in this repository use it, and neither may keep its own
copy of the rules:

  * ``instruments/2026.1/tracks/t2-discrimination/tools/fetch-commons-media.py``
    builds the SCORED real-vs-AI image deck.
  * ``instruments/practice/2026.1/tools/build-practice-corpus.py`` builds the
    UNSCORED practice corpus.

The two corpora must never share an asset, so they must at least share the
definition of what an acceptable asset IS.

Rules encoded here, once:
  * only CC0 / CC-BY / CC-BY-SA / Public domain files are ever accepted;
  * the API is called with a declared User-Agent and hard 429 backoff;
  * assets are re-encoded to progressive JPEG, max edge 800px, <= 150 KB by
    default; a caller may raise the cap and ask for a common target size;
  * the filename is the first 12 hex of sha256 of the ENCODED bytes, so the
    file name is a content address and two identical assets cannot be stored
    under two names.
"""
import hashlib
import io
import re
import time

import requests
from PIL import Image

API = "https://commons.wikimedia.org/w/api.php"
USER_AGENT = "AILX-research/0.1 (https://github.com/; corpus tooling)"

#: The only licences either corpus may ship. Anything else is dropped, loudly.
OK_LICENSE = re.compile(r"^(CC0|CC BY(-SA)? \d|Public domain|PD)", re.I)

#: Markers that a Commons file page claims the image was model-generated.
AI_MARKER = re.compile(
    r"(AI-generated|generated by|artificial intelligence|Midjourney|DALL-?E|"
    r"Stable Diffusion|FLUX|Imagen|Gemini|ChatGPT|Grok|Firefly|Veo|Nova)",
    re.I,
)

MAX_EDGE = 800
MAX_BYTES = 150_000


def session():
    s = requests.Session()
    s.headers.update({"User-Agent": USER_AGENT})
    return s


def api(sess, **params):
    """POST the query API (POST, because title lists overflow a GET URL)."""
    params.update(action="query", format="json")
    last = None
    for attempt in range(8):
        try:
            r = sess.post(API, data=params, timeout=60)
            if r.status_code == 429:
                time.sleep(10 + 10 * attempt)
                continue
            r.raise_for_status()
            return r.json()
        except requests.HTTPError as exc:  # pragma: no cover - network path
            last = exc
            time.sleep(10 + 10 * attempt)
    raise last


def strip_tags(s):
    return re.sub(r"<[^>]+>", "", s or "").strip()


def fetch_bytes(sess, url):
    for attempt in range(8):
        r = sess.get(url, timeout=90)
        if r.status_code == 429:
            time.sleep(8 + 6 * attempt)
            continue
        r.raise_for_status()
        return r.content
    raise RuntimeError(f"persistent 429 for {url}")


def encode(raw, max_edge=MAX_EDGE, target=MAX_BYTES, crop=None, aim=None,
           quality_floor=50):
    """Re-encode to a budgeted progressive JPEG.

    ``crop`` is a (left, top, right, bottom) tuple of fractions to REMOVE from
    each edge before scaling. Some Commons uploads carry a generator watermark
    in a corner; leaving it in would make the item answerable from the badge
    rather than from the picture, which teaches nothing. Any crop is recorded
    in the item's provenance, so the derivative stays honestly attributable.

    ``aim`` asks for a COMMON encoded size rather than merely a ceiling: the
    quality that lands closest to ``aim`` without passing ``target`` is used,
    searching upward as well as downward. Photographs carry sensor noise and
    compress large; generations are smooth and compress small, so a corpus
    encoded to a ceiling alone lets file size classify it without anybody
    looking at a picture. Only a caller that mixes the two classes in one
    corpus needs this; with ``aim=None`` the behaviour is the historical one
    (start at 78, step down until the image fits).
    """
    im = Image.open(io.BytesIO(raw)).convert("RGB")
    if crop is not None:
        left, top, right, bottom = crop
        im = im.crop((int(im.width * left), int(im.height * top),
                      int(im.width * (1 - right)), int(im.height * (1 - bottom))))
    im.thumbnail((max_edge, max_edge))

    def at(quality):
        buf = io.BytesIO()
        im.save(buf, "JPEG", quality=quality, optimize=True, progressive=True)
        return buf.getvalue()

    if aim is not None:
        best = None
        for quality in range(quality_floor, 98):
            data = at(quality)
            if len(data) > target:
                break
            if best is None or abs(len(data) - aim) < abs(len(best) - aim):
                best = data
        # Nothing fits the cap even at the floor: fall through to the ceiling
        # walk below, which is allowed to end over budget and be refused.
        if best is not None:
            return best

    quality = 78
    while True:
        data = at(quality)
        if len(data) <= target or quality <= quality_floor:
            return data
        quality -= 6


def content_name(data):
    """The content address used as a filename: 12 hex of sha256(bytes)."""
    return hashlib.sha256(data).hexdigest()[:12]


def imageinfo(sess, titles, width=1100):
    """Licence + attribution + URL for each title, keyed by Commons title."""
    out = {}
    for i in range(0, len(titles), 40):
        j = api(sess, titles="|".join(titles[i : i + 40]), prop="imageinfo",
                iiprop="url|extmetadata|size|mime", iiurlwidth=width)
        for page in j.get("query", {}).get("pages", {}).values():
            if "imageinfo" not in page:
                continue
            ii = page["imageinfo"][0]
            em = ii.get("extmetadata", {})
            out[page["title"]] = {
                "license": strip_tags(str(em.get("LicenseShortName", {}).get("value", ""))),
                "author": strip_tags(str(em.get("Artist", {}).get("value", ""))),
                "description": strip_tags(str(em.get("ImageDescription", {}).get("value", "")))[:400],
                "source_url": ii["descriptionurl"],
                "thumburl": ii.get("thumburl") or ii["url"],
                "mime": ii.get("mime", ""),
            }
        time.sleep(1.5)
    return out


def page_evidence(sess, titles):
    """Categories + wikitext per title, so a caller can VERIFY a claim.

    Commons category membership is not proof: files that are AI *restorations*
    of real photographs sit in AI categories, and real photographs of an
    AI-themed festival sit there too. A pipeline must read the page itself.
    """
    out = {}
    for i in range(0, len(titles), 20):
        j = api(sess, titles="|".join(titles[i : i + 20]), prop="categories|revisions",
                cllimit="max", rvprop="content", rvslots="main")
        for p in j.get("query", {}).get("pages", {}).values():
            cats = [c["title"] for c in p.get("categories", [])]
            try:
                wikitext = p["revisions"][0]["slots"]["main"]["*"]
            except Exception:
                wikitext = ""
            out[p["title"]] = {"categories": cats, "wikitext": wikitext}
        time.sleep(1.5)
    return out
