/**
 * GENERATED FILE — do not edit by hand.
 *
 * Source of truth: `instruments/practice/2026.1/corpus.json`.
 * Regenerate:     `python3 instruments/practice/2026.1/tools/build-practice-corpus.py`
 * Kept in sync by `packages/report/test/practiceCorpus.test.ts`.
 *
 * The corpus is content-as-data; this module only carries it into the bundle
 * so that `/practice` works in the STATIC export, which can read no file at
 * run time. It reaches no instrument content and performs no I/O.
 */
import type { PracticeItem } from "./practice.js";

/**
 * Version of the corpus, recorded on every practice session so a later
 * content change can never be mistaken for a change in a person's accuracy.
 */

export const PRACTICE_BANK_VERSION = "practice-2026.1-media-3";

export const PRACTICE_BANK: readonly PracticeItem[] = [
  {
    "id": "practice:function:arcade-carriage",
    "family": "function",
    "key": 0,
    "difficulty": "easy",
    "tell": "Nothing connects the horse to the carriage. There are no shafts, no traces and no swingletree — the harness straps end in mid-air on the animal's flank while the vehicle stands behind it as though being drawn. Look for the load path before you look at the style.",
    "material": {
      "kind": "image",
      "src": "practice-media/0eb398f1bf8d.jpg",
      "alt": "A colonnaded street of a grand arcaded building at low sun, with a horse and a covered carriage standing on the cobbles."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Hotel De Oriente Philippines late 1800's to early 1900's.jpg",
      "author": "Irishandys",
      "license": "CC0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Hotel_De_Oriente_Philippines_late_1800%27s_to_early_1900%27s.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px",
      "generator_evidence": "AI-generated"
    }
  },
  {
    "id": "practice:function:bicycle-chain-mid-air",
    "family": "function",
    "key": 0,
    "difficulty": "easy",
    "tell": "Follow the chain. Both of its runs leave the chainring and pass straight across the face of the rear wheel — over the tyre and the rim, around no sprocket at all — and one branch climbs vertically through the open frame and stops in the air. A chain is a closed loop between two toothed wheels, or the machine does not move.",
    "material": {
      "kind": "image",
      "src": "practice-media/29bf392d793c.jpg",
      "alt": "A blue city bicycle with a wire front basket leaning against a brick wall on a pavement."
    },
    "credit": {
      "origin": "generated",
      "model": "google/gemini-2.5-flash-image",
      "provider": "google",
      "prompt": "An ordinary city bicycle leaning against a brick wall in daylight, photographed from the drive side. The chain runs off the front chainring and ends in mid-air beside the rear wheel: it does not pass around the rear sprocket, and the rear sprocket is bare. Sharp close detail of the frame and wheels, 50mm. Photorealistic documentary photograph, natural available light, no text, no lettering, no numbers, no signage and no watermark anywhere in the frame.",
      "author": "AILX practice corpus (prompted generation)",
      "license": "CC0",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal",
      "rights_basis": "Gemini API Terms, \"Use of Generated Content\": \"Google won't claim ownership over that content.\" Output carries an invisible SynthID watermark; AI origin must be disclosed, never denied. OpenRouter ToS s6.1: model terms flow through; OpenRouter claims no ownership of Output.",
      "generator_evidence": "generated by google/gemini-2.5-flash-image on 2026-08-29; see generated.json"
    }
  },
  {
    "id": "practice:function:donkey-cart",
    "family": "function",
    "key": 0,
    "difficulty": "easy",
    "tell": "The painted finish is not the evidence — paintings are not fakes, and a photograph can be styled to look like one. The wheel is: a third spoked wheel stands under the donkey's belly, ahead of the cart's own wheel and on a different line, joined to no axle, no frame and no hub. Ask what carries the load before you judge the surface.",
    "material": {
      "kind": "image",
      "src": "practice-media/868797bb5749.jpg",
      "alt": "A donkey drawing a wooden cart along a dirt road, a man standing on the cart behind a person lying under a blanket.",
      "style": "painterly"
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Burro Ambulancia.jpg",
      "author": "161803cesar",
      "license": "Public domain",
      "source_url": "https://commons.wikimedia.org/wiki/File:Burro_Ambulancia.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px",
      "generator_evidence": "AI-generated"
    }
  },
  {
    "id": "practice:function:donkey-cart-tyres",
    "family": "function",
    "key": 1,
    "difficulty": "medium",
    "tell": "The rig is improvised — a timber bed on a steel frame, motor-car wheels, chain traces — and every joint still closes: chain from the animals to the shaft, shaft to the cart, wheel on the hub it turns on. Trace the linkage before you call it. Working vehicles are often ugly and always connected.",
    "material": {
      "kind": "image",
      "src": "practice-media/32650e76d7ee.jpg",
      "alt": "A team of donkeys drawing a flat wooden cart on motor-car wheels along a dirt road, with two men riding on it."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Liberty Mugari.jpg",
      "author": "Liberty Mugari",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Liberty_Mugari.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:function:fried-mushrooms",
    "family": "function",
    "key": 0,
    "difficulty": "medium",
    "tell": "Several pieces are cuts no mushroom has — a dark gilled hollow opening in the middle of a smooth dome, and a piece that closes into a hollow ring. Food is a good place to look: texture is easy to fake, anatomy is not.",
    "material": {
      "kind": "image",
      "src": "practice-media/f6353153e8b4.jpg",
      "alt": "A dark bowl of golden fried mushroom pieces scattered with chopped herbs, on a dark wooden table."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:פטריות מטוגנות.png",
      "author": "Eladkarmel",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:%D7%A4%D7%98%D7%A8%D7%99%D7%95%D7%AA_%D7%9E%D7%98%D7%95%D7%92%D7%A0%D7%95%D7%AA.png",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal",
      "generator_evidence": "AI-generated"
    }
  },
  {
    "id": "practice:function:frying-chanterelles",
    "family": "function",
    "key": 1,
    "difficulty": "medium",
    "tell": "Every piece is a consistent part of one mushroom species — cap, gilled underside and stalk in the right relationship — and each cut edge matches the flesh it came from. Real food varies in size; it never varies in anatomy.",
    "material": {
      "kind": "image",
      "src": "practice-media/92e2816b8438.jpg",
      "alt": "Orange mushrooms and sliced onion cooking in a pan with a wooden spoon."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Frying red pine mushrooms in a pan (54064465568).jpg",
      "author": "AS Photography from Poland",
      "license": "CC BY 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Frying_red_pine_mushrooms_in_a_pan_(54064465568).jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:function:market-bowls",
    "family": "function",
    "key": 1,
    "difficulty": "hard",
    "tell": "Rows of near-identical bowls look like a tiled texture, and tiling is a genuine tell — but here each bowl holds a different count heaped to a different height with its own shadow. Repetition with variation is a stall; repetition without it is a texture.",
    "material": {
      "kind": "image",
      "src": "practice-media/737061693633.jpg",
      "alt": "Rows of small coloured plastic bowls holding chillies, berries and beans on a market stall."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Capsicum baccatum in Saúde flea market, São Paulo, Brazil.jpg",
      "author": "Wilfredor",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Capsicum_baccatum_in_Sa%C3%BAde_flea_market,_S%C3%A3o_Paulo,_Brazil.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal"
    }
  },
  {
    "id": "practice:function:meadow-monitor",
    "family": "function",
    "key": 0,
    "difficulty": "easy",
    "tell": "The monitor is mounted on a slab that is half keyboard and half plinth — not a laptop, not a stand, not any object that could hold a screen up. Generators assemble the PARTS of familiar things without the joint that makes them work.",
    "material": {
      "kind": "image",
      "src": "practice-media/66826f61c6cb.jpg",
      "alt": "A flat-panel monitor showing a goldfish, standing in long meadow grass under a bright sun and scattered cloud."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Frutiger aero-style wallpaper (cropped).png",
      "author": "Stable Diffusion по запросу Tucvbif",
      "license": "Public domain",
      "source_url": "https://commons.wikimedia.org/wiki/File:Frutiger_aero-style_wallpaper_(cropped).png",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px",
      "generator_evidence": "Generated by"
    }
  },
  {
    "id": "practice:function:nursery-trolley",
    "family": "function",
    "key": 1,
    "difficulty": "medium",
    "tell": "An unfamiliar machine is not an impossible one. Follow it through: the operator sits over the drive, the crates rest on the bed that carries them, and the flattened track behind matches its wheels.",
    "material": {
      "kind": "image",
      "src": "practice-media/2a37d6c58497.jpg",
      "alt": "A person driving a small tractor along a grass track, with four baskets of leafy seedlings carried on a rear frame."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Harvest (20110505-RD-LSC-0157).jpg",
      "author": "USDAgov",
      "license": "Public domain",
      "source_url": "https://commons.wikimedia.org/wiki/File:Harvest_(20110505-RD-LSC-0157).jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:function:preserve-jars",
    "family": "function",
    "key": 0,
    "difficulty": "medium",
    "tell": "Look at the tall jar. Its contents repeat as near-identical stamped discs in rows, which is a tiled texture rather than a jar of real produce, and the loose mushrooms do not settle on one species — one cap is furred, its neighbour smooth, and the same stalk carries both gills and pores.",
    "material": {
      "kind": "image",
      "src": "practice-media/53426c92a999.jpg",
      "alt": "A still life of mushrooms, preserving jars, a bowl of red-capped fungi and books on a cloth-covered table."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:פטריות במחסן.png",
      "author": "Eladkarmel",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:%D7%A4%D7%98%D7%A8%D7%99%D7%95%D7%AA_%D7%91%D7%9E%D7%97%D7%A1%D7%9F.png",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, corner cropped to remove a generator watermark",
      "generator_evidence": "AI-generated"
    }
  },
  {
    "id": "practice:function:sesame-buns",
    "family": "function",
    "key": 1,
    "difficulty": "easy",
    "tell": "An overhead food shot is the format generators imitate, so the reflex is to distrust it. The seeds settle it: the scatter is different on every bun, seeds sit on the crust and on the cloth around the plate, and no two buns share an outline.",
    "material": {
      "kind": "image",
      "src": "practice-media/dbf60815ed2a.jpg",
      "alt": "Three round sesame-topped buns arranged on a long dark plate, seen from directly above."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Mixed mushroom buns, pan fried - San Francisco, CA.jpg",
      "author": "Daderot",
      "license": "CC0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Mixed_mushroom_buns,_pan_fried_-_San_Francisco,_CA.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:function:wicker-horn",
    "family": "function",
    "key": 0,
    "difficulty": "hard",
    "tell": "The horn is woven in believable rows at its mouth, then the weave dissolves into a smooth spiral at the tip that no basket could be made in. Regular manufactured pattern that stops being regular is the tell.",
    "material": {
      "kind": "image",
      "src": "practice-media/5130b2aba3d0.jpg",
      "alt": "A wicker cornucopia spilling fruit and gourds across a bare wooden table against dark panelling."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Aux cuisines du chateau, une corne dabondance IA Dall e Bing 18 nov 2023 Lamiot 01.png",
      "author": "Lamiot",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Aux_cuisines_du_chateau,_une_corne_dabondance_IA_Dall_e_Bing_18_nov_2023_Lamiot_01.png",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, corner cropped to remove a generator watermark",
      "generator_evidence": "Dall-e"
    }
  },
  {
    "id": "practice:physics:autumn-apse",
    "family": "physics",
    "key": 1,
    "difficulty": "hard",
    "tell": "The colour is doing the lying here, not the picture. Saturation is a processing choice; what matters is that the stone courses run continuously into the curve of the apse and the shadows all agree. Vivid is not evidence.",
    "material": {
      "kind": "image",
      "src": "practice-media/f1f934a75fd3.jpg",
      "alt": "A small stone church with a rounded apse standing among yellow autumn trees under a deep blue sky."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Kaplica grobowa rodziny Potockich P1680784 Peczera.jpg",
      "author": "Posterrr",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Kaplica_grobowa_rodziny_Potockich_P1680784_Peczera.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal"
    }
  },
  {
    "id": "practice:physics:chapel-golden-hour",
    "family": "physics",
    "key": 0,
    "difficulty": "medium",
    "tell": "The picture wears late golden light, yet nothing in it has a shadow — not the chapel, not the bush, not the dry-stone wall. Both faces of the building are lit equally, so there is no direction to the sun at all. A generator copies the LOOK of late light without running the geometry that light implies.",
    "material": {
      "kind": "image",
      "src": "practice-media/3f7b8b77c076.jpg",
      "alt": "A small stone chapel with a tiled roof and a roof cross, on a grassy hilltop behind dry-stone walls."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:AI generated Image Marienkapelle Zeil am Main 1727.jpg",
      "author": "Start with AI Gemini 3.1 Pro (Thinking), continued with AI Gemini 3.6 Flash (Thinking)",
      "license": "Public domain",
      "source_url": "https://commons.wikimedia.org/wiki/File:AI_generated_Image_Marienkapelle_Zeil_am_Main_1727.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px",
      "generator_evidence": "AI-generated"
    }
  },
  {
    "id": "practice:physics:hilltop-chapel-night",
    "family": "physics",
    "key": 1,
    "difficulty": "hard",
    "tell": "It looks impossible because it is a long exposure. A slow shutter is what smears cloud into streaks and turns one small lamp into a steady glow. An unusual camera setting is not an artefact.",
    "material": {
      "kind": "image",
      "src": "practice-media/83a8ef7fa6e3.jpg",
      "alt": "A tiny chapel on a rocky summit at night, one window lit, under a dark streaked sky."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Світло в капличці.jpg",
      "author": "Serhii Zysko",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%B2%D1%96%D1%82%D0%BB%D0%BE_%D0%B2_%D0%BA%D0%B0%D0%BF%D0%BB%D0%B8%D1%87%D1%86%D1%96.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:physics:keble-chapel-banding",
    "family": "physics",
    "key": 1,
    "difficulty": "medium",
    "tell": "The brick banding is so regular that it reads as a tiled texture. Check it the way you would check a generator: the bands run unbroken around every corner and behind every downpipe, and every buttress shadow falls the same way. Regularity that survives inspection is masonry.",
    "material": {
      "kind": "image",
      "src": "practice-media/2192502efd63.jpg",
      "alt": "A large Victorian chapel in banded red and cream brick with tall traceried windows, on a lawn under a blue sky."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Keble College Chapel Exterior, Oxford, UK - Diliff.jpg",
      "author": "Diliff",
      "license": "CC BY-SA 3.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Keble_College_Chapel_Exterior,_Oxford,_UK_-_Diliff.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal"
    }
  },
  {
    "id": "practice:physics:ladder-one-stile",
    "family": "physics",
    "key": 0,
    "difficulty": "medium",
    "tell": "The ladder standing against the wall has ten close rungs; the ladder-shaped shadow cast on the wall beside it has four widely spaced ones. Light can stretch, skew or blur a shadow, but it cannot delete six rungs from it. Compare a shadow with the object that casts it, not only with the direction of the sun.",
    "material": {
      "kind": "image",
      "src": "practice-media/ae72f84893e4.jpg",
      "alt": "A weathered wooden ladder leaning against the rendered wall of a house beside a window, with a garden and fence behind it."
    },
    "credit": {
      "origin": "generated",
      "model": "google/gemini-3.1-flash-lite-image",
      "provider": "google",
      "prompt": "A wooden ladder leaning against the rendered wall of a house on a sunny day in an ordinary back garden. Each rung of the ladder is fixed to only ONE of the two side rails; the other end of every rung stops short in the air and never reaches the second rail. Hard sunlight, sharp timber grain, 35mm. Photorealistic documentary photograph, natural available light, no text, no lettering, no numbers, no signage and no watermark anywhere in the frame.",
      "author": "AILX practice corpus (prompted generation)",
      "license": "CC0",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px",
      "rights_basis": "Gemini API Terms, \"Use of Generated Content\": \"Google won't claim ownership over that content.\" Output carries an invisible SynthID watermark; AI origin must be disclosed, never denied. OpenRouter ToS s6.1: model terms flow through; OpenRouter claims no ownership of Output.",
      "generator_evidence": "generated by google/gemini-3.1-flash-lite-image on 2026-08-29; see generated.json"
    }
  },
  {
    "id": "practice:physics:moated-palace-reflection",
    "family": "physics",
    "key": 1,
    "difficulty": "medium",
    "tell": "Wind has broken the moat into chop, so there is no mirror image to check — and that is not suspicious. A rippled surface scatters the sky instead of returning the building; you only get a reflection when the water is still. What holds instead is the waterline: the chop shrinks and its contrast falls smoothly towards the far bank, the swans sit in the water rather than on it, and the balustrade shadows agree with the sun. An absent reflection is a fact about the weather, not about the pipeline.",
    "material": {
      "kind": "image",
      "src": "practice-media/e35d0d164fea.jpg",
      "alt": "A long baroque brick palace with pale stone dressings, seen across a wide expanse of wind-rippled water."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Nordkirchen, Schloss Nordkirchen -- 2015 -- 7797.jpg",
      "author": "Dietmar Rabich",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Nordkirchen,_Schloss_Nordkirchen_--_2015_--_7797.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:physics:promenade-lamp-posts",
    "family": "physics",
    "key": 0,
    "difficulty": "medium",
    "tell": "The sun is hard enough to put crisp shadows under the visitors and their benches, yet the lamp-posts and the parapet lay none at all on the paving. It is the DISAGREEMENT that convicts, not the absence: objects sharing one plaza share one sun, and this scene was lit item by item instead of being solved once.",
    "material": {
      "kind": "image",
      "src": "practice-media/0aea741d8272.jpg",
      "alt": "A lakeside promenade with benches, lamp-posts and many visitors, a city skyline and a large statue across the water."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:చెరువుకట్ట.png",
      "author": "Author:Gemini Ai",
      "license": "Public domain",
      "source_url": "https://commons.wikimedia.org/wiki/File:%E0%B0%9A%E0%B1%86%E0%B0%B0%E0%B1%81%E0%B0%B5%E0%B1%81%E0%B0%95%E0%B0%9F%E0%B1%8D%E0%B0%9F.png",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, corner cropped to remove a generator watermark",
      "generator_evidence": "Gemini"
    }
  },
  {
    "id": "practice:physics:tower-city-haze",
    "family": "physics",
    "key": 0,
    "difficulty": "easy",
    "tell": "Glass is a mirror. These towers are glazed top to bottom in bright hazy sun and not one pane returns anything — no sky, no cloud, no neighbouring tower, no bright edge where a face turns — while the ponds below them mirror the trees perfectly well. Ask what a surface ought to be reflecting, not only where the shadows are.",
    "material": {
      "kind": "image",
      "src": "practice-media/143a10347240.jpg",
      "alt": "An elevated view over a city of glass towers threaded with waterways, woodland and low roofs with solar panels.",
      "style": "render"
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Solarpunk, a positive possible near-future.jpg",
      "author": "Prototyperspective",
      "license": "CC0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Solarpunk,_a_positive_possible_near-future.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal",
      "generator_evidence": "generated by"
    }
  },
  {
    "id": "practice:social:exam-hall-crest",
    "family": "social",
    "key": 0,
    "difficulty": "medium",
    "tell": "The crest and lettering on the uniform dissolve into unreadable marks at a resolution where individual stitches are sharp. An institution's insignia is a claim about which institution — and this one names nothing.",
    "material": {
      "kind": "image",
      "src": "practice-media/cd436a971255.jpg",
      "alt": "A large hall of students in white polo shirts and face masks writing at individual desks."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:HONG KONG SCHOOLS COVID 19.png",
      "author": "midjourney",
      "license": "Public domain",
      "source_url": "https://commons.wikimedia.org/wiki/File:HONG_KONG_SCHOOLS_COVID_19.png",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px",
      "generator_evidence": "AI-generated"
    }
  },
  {
    "id": "practice:social:genkan-shoes-inside",
    "family": "social",
    "key": 0,
    "difficulty": "medium",
    "tell": "The raised step is the boundary between outside and inside. Outdoor shoes are left on the tiled floor below it, turned back towards the door; only slippers belong on the wood. Here four pairs of outdoor shoes stand up on the raised floor pointing indoors while two pairs sit correctly below, so the picture obeys and breaks the same rule at once.",
    "material": {
      "kind": "image",
      "src": "practice-media/bafb7239587b.jpg",
      "alt": "The entrance hall of a house: a tiled floor at door level, a raised wooden floor above a single step, a shoe cupboard, and several pairs of shoes."
    },
    "credit": {
      "origin": "generated",
      "model": "google/gemini-2.5-flash-image",
      "provider": "google",
      "prompt": "The entrance hall of an ordinary Japanese home: a lowered tiled step at the door and a raised wooden floor above it, a shoe cupboard, a row of house slippers. Four pairs of outdoor leather shoes and trainers stand ON the raised wooden floor above the step, all of them pointing inwards towards the house. Soft daylight from the open door, no people, 35mm. Photorealistic documentary photograph, natural available light, no text, no lettering, no numbers, no signage and no watermark anywhere in the frame.",
      "author": "AILX practice corpus (prompted generation)",
      "license": "CC0",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal",
      "rights_basis": "Gemini API Terms, \"Use of Generated Content\": \"Google won't claim ownership over that content.\" Output carries an invisible SynthID watermark; AI origin must be disclosed, never denied. OpenRouter ToS s6.1: model terms flow through; OpenRouter claims no ownership of Output.",
      "generator_evidence": "generated by google/gemini-2.5-flash-image on 2026-08-29; see generated.json"
    }
  },
  {
    "id": "practice:social:kilt-pleats-front",
    "family": "social",
    "key": 0,
    "difficulty": "medium",
    "tell": "A kilt is flat at the front: one broad apron crosses the body and every pleat is sewn into the back. Here the knife pleats run the full width of the front and no apron edge exists anywhere, so the garment could not be wrapped or fastened. Ask how clothing is CONSTRUCTED before you judge how it is patterned.",
    "material": {
      "kind": "image",
      "src": "practice-media/e5a4b8afadfb.jpg",
      "alt": "A man in a tweed jacket, waistcoat, tartan kilt, sporran and knee socks standing on a stone terrace in front of a low balustrade."
    },
    "credit": {
      "origin": "generated",
      "model": "openai/gpt-5-image",
      "provider": "openai",
      "prompt": "A man in full Scottish Highland dress standing on a stone terrace, photographed from directly in front at eye level, full length. The kilt's deep knife pleats fall across the FRONT of his body facing the camera; there is no flat apron panel at the front. Overcast daylight, 50mm, sharp wool texture. Photorealistic documentary photograph, natural available light, no text, no lettering, no numbers, no signage and no watermark anywhere in the frame.",
      "author": "AILX practice corpus (prompted generation)",
      "license": "CC0",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal",
      "rights_basis": "OpenAI Terms of Use, \"Ownership of content\": \"you ... (b) own the Output. We hereby assign to you all our right, title, and interest, if any, in and to Output.\" C2PA/SynthID provenance embedded; no competing-model training. OpenRouter ToS s6.1: model terms flow through; OpenRouter claims no ownership of Output.",
      "generator_evidence": "generated by openai/gpt-5-image on 2026-08-29; see generated.json"
    }
  },
  {
    "id": "practice:social:market-street-crowd",
    "family": "social",
    "key": 1,
    "difficulty": "medium",
    "tell": "This is what a real crowd encodes: different trades, ages and styles of dress in one frame, some people carrying loads on the head and some not. A generated crowd tends to dress everybody the same way.",
    "material": {
      "kind": "image",
      "src": "practice-media/f0e85694fc56.jpg",
      "alt": "A busy open-air market street lined with stalls under canopies, with many shoppers walking between them."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Accra Market, Accra (P1100247).jpg",
      "author": "Matti Blume",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:Accra_Market,_Accra_(P1100247).jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:social:shopfront-signage",
    "family": "social",
    "key": 1,
    "difficulty": "medium",
    "tell": "The signage is the check, and you do not need to read the script to run it: the same letterforms recur, correctly formed, across two lines of one board and again on its neighbours, with a global brand name spelled correctly among the local ones. Generated signage melts between signs into letter-shaped marks.",
    "material": {
      "kind": "image",
      "src": "practice-media/a96b9aed53a3.jpg",
      "alt": "A narrow city street with parked motorcycles, a handcart and shopfronts with painted signs."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:People purchasing Mangoes in Powerpowet station road.jpg",
      "author": "iMahesh",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:People_purchasing_Mangoes_in_Powerpowet_station_road.jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
  {
    "id": "practice:social:temple-plaza-crowd",
    "family": "social",
    "key": 0,
    "difficulty": "hard",
    "tell": "Look for what people are DOING, not what they wear. The stalls stand laden but nobody buys, nobody carries a load, leads an animal or works; and the tiered seating is full of an audience facing an empty plaza with nothing staged in front of it. The generator drew a population and forgot to give it business.",
    "material": {
      "kind": "image",
      "src": "practice-media/9582563e02be.jpg",
      "alt": "A wide sunlit plaza before a columned temple, crowded with people in robes, with tiered stone seating to one side.",
      "style": "render"
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:Sanctuary of Ercole Vincitore Tivoli Render Model Inside Gemini-generated.png",
      "author": "Google Gemini; generated by Horst-schlaemma",
      "license": "Public domain",
      "source_url": "https://commons.wikimedia.org/wiki/File:Sanctuary_of_Ercole_Vincitore_Tivoli_Render_Model_Inside_Gemini-generated.png",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal",
      "generator_evidence": "Gemini"
    }
  },
  {
    "id": "practice:social:village-cricket-stumps",
    "family": "social",
    "key": 0,
    "difficulty": "medium",
    "tell": "A cricket wicket is three stumps standing nine inches wide with two bails laid across their tops. Behind this batsman are two thin stumps a hand's width apart with nothing resting on them — a wicket that cannot be broken, which is the whole point of it. Count the parts of the equipment a scene is built around.",
    "material": {
      "kind": "image",
      "src": "practice-media/186089557433.jpg",
      "alt": "A batsman in whites playing a shot on a village green in summer, with two fielders in front of him and a wicket at his heels."
    },
    "credit": {
      "origin": "generated",
      "model": "openai/gpt-5.4-image-2",
      "provider": "openai",
      "prompt": "A village cricket match on an English green on a summer afternoon, seen from square of the wicket. The wicket behind the batsman has only TWO stumps standing in the ground and no bails resting across their tops. Players in whites, long grass boundary, oak trees behind, 200mm telephoto, shallow depth of field. Photorealistic documentary photograph, natural available light, no text, no lettering, no numbers, no signage and no watermark anywhere in the frame.",
      "author": "AILX practice corpus (prompted generation)",
      "license": "CC0",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px, cropped to reframe, so the aspect ratio carries no signal",
      "rights_basis": "OpenAI Terms of Use, \"Ownership of content\": \"you ... (b) own the Output. We hereby assign to you all our right, title, and interest, if any, in and to Output.\" C2PA/SynthID provenance embedded; no competing-model training. OpenRouter ToS s6.1: model terms flow through; OpenRouter claims no ownership of Output.",
      "generator_evidence": "generated by openai/gpt-5.4-image-2 on 2026-08-29; see generated.json"
    }
  },
  {
    "id": "practice:social:wayside-shrine",
    "family": "social",
    "key": 1,
    "difficulty": "hard",
    "tell": "An unfamiliar building type reads as invented, and this is a real vernacular form. The render, the water staining and the vegetation are all consistent with one neglected structure. Unfamiliar is not the same as wrong.",
    "material": {
      "kind": "image",
      "src": "practice-media/f5e60d898382.jpg",
      "alt": "A small whitewashed wayside shrine with a domed top and an arched opening, standing beside an overgrown bank."
    },
    "credit": {
      "origin": "commons",
      "commons_title": "File:2024 Kapliczka Matki Bożej w Jaszkowej Górnej (1).jpg",
      "author": "Jacek Halicki",
      "license": "CC BY-SA 4.0",
      "source_url": "https://commons.wikimedia.org/wiki/File:2024_Kapliczka_Matki_Bo%C5%BCej_w_Jaszkowej_G%C3%B3rnej_(1).jpg",
      "retrieved": "2026-08-29",
      "derivative": "re-encoded JPEG, max edge 800px"
    }
  },
];
